import { BaseModel } from '../../_base/crud';
import { Address } from './address.model';
import { SocialNetworks } from './social-networks.model';

export class User extends BaseModel {
    id: number;
    // username: string;
    companyDirector:string;
    natureBusiness :string;
    nameCompany:string;
    accountType:string;
    _id:string;
    password: string;
    hash: string;
    totalEquity:number;
    salt: string;
    emailAddress: string;
    accessToken: string;
    refreshToken: string;
    roles: number[];
    addField1:string;
    addField2:string;
    addField3:string;
    addField4:string;
    pic: string;
    firstName: string;
    lastName: string;
    firstNameTwo: string;
    lastNameTwo: string;
    userStatus:string;
    date:Date;

    employmentStatus:string;
    nameEmployer:string;
    nameCompanyEm:string;
    investmentKnowledge:string;
    netWorth:string;
    // occupation: string;
	// companyName: string;
	phoneNumber: string;
    // address: Address;
    // socialNetworks: SocialNetworks;
    countryCitizenship:string;
    countryResidence:string;
    clear(): void {
        this.id = undefined;
        // this.username = '';
        this.accountType = 'Individual Account';
        this.companyDirector = '';
        this.natureBusiness = '';
        this.nameCompany = '';
        this.password = '';
        this.hash = '';
        this.emailAddress = '';
        this.roles = [];
        this.firstName = '';
        this.lastName = '';
        this.firstNameTwo = '';
        this.lastNameTwo = '';
        this.addField1 = '';
        this.addField2 = '';
        this.addField3 = '';
        this.addField4 = '';
        this.lastName = '';
        this.accessToken = 'access-token-' + Math.random();
        this.refreshToken = 'access-token-' + Math.random();
        this.pic = './assets/media/users/default.jpg';
        this.date = new Date();
        // this.occupation = '';
        // this.companyName = '';
        this.phoneNumber = '';
        // this.address = new Address();
        // this.address.clear();
        // this.socialNetworks = new SocialNetworks();
        // this.socialNetworks.clear();
        this.countryCitizenship = '';
        this.countryResidence = '';

        this.employmentStatus ='Other';
        this.nameEmployer ='';
        this.nameCompanyEm ='';
        this.investmentKnowledge ='Beginner';
        this.netWorth ='£25,000 - £50,000';
    }
}
